package ru.finny.pet.ui

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Brush
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.ExperimentalTextApi
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontVariation
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import ru.finny.pet.R

/** 8dp spacing scale (M3 layout guidance). */
object Space {
    val xs = 4.dp
    val sm = 8.dp
    val md = 16.dp
    val lg = 24.dp
    val xl = 32.dp
}

/** Fixed brand colours that must not follow the theme (pet artwork, coin). */
val CoinGold = Color(0xFFFFC94D)
val CoinGoldDark = Color(0xFFD9A400)

/** Purple → magenta gradient of the ЛЦТ template: hero surfaces carry white content. */
val BrandGradient = Brush.linearGradient(listOf(Color(0xFF310F53), Color(0xFF520978), Color(0xFF8E1F8F)))
val OnBrand = Color.White

/** Montserrat (SIL OFL 1.1) — the template typeface; one variable file, weights via wght axis (API 26+). */
@OptIn(ExperimentalTextApi::class)
private fun montserrat(weight: FontWeight) = Font(R.font.montserrat, weight, variationSettings = FontVariation.Settings(weight, androidx.compose.ui.text.font.FontStyle.Normal))
val Montserrat = FontFamily(montserrat(FontWeight.Normal), montserrat(FontWeight.Medium), montserrat(FontWeight.SemiBold), montserrat(FontWeight.Bold), montserrat(FontWeight.ExtraBold))

/**
 * M3 type scale in Montserrat, nudged up ~2sp for readers aged 7–11 (ТЗ 3.6: body ≥ 16sp).
 * Montserrat is wide, so tracking is tighter than the Roboto defaults.
 */
private val FinnyTypography = Typography(
    displayMedium = TextStyle(fontFamily = Montserrat, fontSize = 44.sp, lineHeight = 52.sp, fontWeight = FontWeight.ExtraBold, letterSpacing = (-0.5).sp),
    displaySmall = TextStyle(fontFamily = Montserrat, fontSize = 36.sp, lineHeight = 44.sp, fontWeight = FontWeight.ExtraBold, letterSpacing = (-0.5).sp),
    headlineLarge = TextStyle(fontFamily = Montserrat, fontSize = 32.sp, lineHeight = 40.sp, fontWeight = FontWeight.Bold),
    headlineMedium = TextStyle(fontFamily = Montserrat, fontSize = 28.sp, lineHeight = 36.sp, fontWeight = FontWeight.Bold),
    headlineSmall = TextStyle(fontFamily = Montserrat, fontSize = 24.sp, lineHeight = 32.sp, fontWeight = FontWeight.Bold),
    titleLarge = TextStyle(fontFamily = Montserrat, fontSize = 22.sp, lineHeight = 28.sp, fontWeight = FontWeight.Bold),
    titleMedium = TextStyle(fontFamily = Montserrat, fontSize = 18.sp, lineHeight = 24.sp, fontWeight = FontWeight.SemiBold),
    titleSmall = TextStyle(fontFamily = Montserrat, fontSize = 16.sp, lineHeight = 20.sp, fontWeight = FontWeight.SemiBold),
    bodyLarge = TextStyle(fontFamily = Montserrat, fontSize = 17.sp, lineHeight = 25.sp, fontWeight = FontWeight.Medium),
    bodyMedium = TextStyle(fontFamily = Montserrat, fontSize = 16.sp, lineHeight = 22.sp, fontWeight = FontWeight.Medium),
    bodySmall = TextStyle(fontFamily = Montserrat, fontSize = 14.sp, lineHeight = 18.sp, fontWeight = FontWeight.Medium),
    labelLarge = TextStyle(fontFamily = Montserrat, fontSize = 16.sp, lineHeight = 20.sp, fontWeight = FontWeight.Bold),
    labelMedium = TextStyle(fontFamily = Montserrat, fontSize = 14.sp, lineHeight = 16.sp, fontWeight = FontWeight.SemiBold),
    labelSmall = TextStyle(fontFamily = Montserrat, fontSize = 12.sp, lineHeight = 16.sp, fontWeight = FontWeight.SemiBold),
)

/** Rounder than the M3 defaults (expressive "large-increased" flavour) — friendlier for children. */
private val FinnyShapes = Shapes(
    extraSmall = RoundedCornerShape(8.dp),
    small = RoundedCornerShape(12.dp),
    medium = RoundedCornerShape(16.dp),
    large = RoundedCornerShape(24.dp),
    extraLarge = RoundedCornerShape(32.dp),
)

/** Fixed brand scheme generated by tools/office/gen_theme.js; light and dark follow the system. */
@Composable
fun FinnyTheme(darkTheme: Boolean = isSystemInDarkTheme(), content: @Composable () -> Unit) {
    MaterialTheme(
        colorScheme = if (darkTheme) DarkScheme else LightScheme,
        typography = FinnyTypography,
        shapes = FinnyShapes,
        content = content,
    )
}

/**
 * Semantic colours. Needs map to scheme roles so the dark theme works; [success] is a fixed green
 * for "done / grew / correct" marks — the brand palette has no green and a check must read as a check.
 */
object FinnyColors {
    private val dark: Boolean @Composable get() = MaterialTheme.colorScheme == DarkScheme
    /** Card ground: white on the light theme; in the dark theme the lowest surface is darker than the ground, so cards step up instead. */
    val card: Color @Composable get() = if (dark) MaterialTheme.colorScheme.surfaceContainerLow else MaterialTheme.colorScheme.surfaceContainerLowest
    val hunger: Color @Composable get() = MaterialTheme.colorScheme.secondary
    val clean: Color @Composable get() = MaterialTheme.colorScheme.tertiary
    val mood: Color @Composable get() = success
    val success: Color @Composable get() = if (dark) Color(0xFF6BD495) else Color(0xFF1B7F4C)
}
