#!/usr/bin/env bash
# Converts rendered pet frames (PNG, transparent) into app/src/main/res/drawable-nodpi/*.webp
# and regenerates ui/PetSprites.kt with explicit R references (so R8 resource shrinking keeps them).
# Usage: tools/art/import_sprites.sh <dir with pet_*.png> [size=512] [quality=88]
set -euo pipefail
cd "$(dirname "$0")/../.."
SRC="$1"; SIZE="${2:-512}"; Q="${3:-88}"
OUT=app/src/main/res/drawable-nodpi
KT=app/src/main/java/ru/finny/pet/PetSprites.kt
mkdir -p "$OUT"; rm -f "$OUT"/pet_*.webp
for f in "$SRC"/pet_*.png; do
  n=$(basename "$f" .png)
  cwebp -quiet -q "$Q" -alpha_q 90 -resize "$SIZE" "$SIZE" -m 6 "$f" -o "$OUT/$n.webp"
done
{
  echo "package ru.finny.pet"
  echo
  echo "import ru.finny.pet.R"
  echo
  echo "// Generated by tools/art/import_sprites.sh from tools/art/pet.py renders. Do not edit by hand."
  echo "object PetSprites {"
  echo "    private val ids: Map<String, Int> = mapOf("
  for f in "$OUT"/pet_*.webp; do n=$(basename "$f" .webp); echo "        \"$n\" to R.drawable.$n,"; done
  echo "    )"
  echo
  echo "    /** Resource for species/colour/stage/face; falls back to the orange cat so a content typo never crashes. */"
  echo "    fun id(species: String, colorId: String, stage: Int, face: String): Int ="
  echo "        ids[\"pet_\${species}_\${colorId}_\${stage.coerceIn(0, 2)}_\$face\"] ?: ids.getValue(\"pet_cat_orange_0_happy\")"
  echo "}"
} > "$KT"
echo "imported $(ls "$OUT"/pet_*.webp | wc -l | tr -d ' ') sprites, $(du -sh "$OUT" | cut -f1) total"
