"""Converts rendered pet frames (PNG, transparent) into app/src/main/res/drawable-nodpi/*.webp and regenerates
PetSprites.kt with explicit R references (so R8 resource shrinking keeps them) for every pet_*.webp there.
Sprites that are not in the source dir stay as they are; to drop one, delete its webp and re-run.

Usage: python tools/art/import_sprites.py <dir with pet_*.png> [size=512]
"""
import sys
from pathlib import Path
from PIL import Image

MAIN = Path(__file__).resolve().parents[2] / "app" / "src" / "main"
OUT = MAIN / "res" / "drawable-nodpi"
KT = MAIN / "java" / "ru" / "finny" / "pet" / "PetSprites.kt"
KT_TEMPLATE = """package ru.finny.pet

import ru.finny.pet.R

// Generated by tools/art/import_sprites.py from tools/art/pet.py renders. Do not edit by hand.
object PetSprites {
    private val ids: Map<String, Int> = mapOf(
@ENTRIES@    )

    /** Resource for species/colour/stage/face; falls back to the orange cat so a content typo never crashes. */
    fun id(species: String, colorId: String, stage: Int, face: String): Int =
        ids["pet_${species}_${colorId}_${stage.coerceIn(0, 2)}_$face"] ?: ids.getValue("pet_cat_orange_0_happy")
}
"""

src, size = Path(sys.argv[1]), int(sys.argv[2]) if len(sys.argv) > 2 else 512
OUT.mkdir(parents=True, exist_ok=True)
pngs = sorted(src.glob("pet_*.png"))
for png in pngs:
    im = Image.open(png).convert("RGBA").resize((size, size), Image.LANCZOS)
    im.save(OUT / f"{png.stem}.webp", "WEBP", quality=88, alpha_quality=90, method=6)

webps = sorted(OUT.glob("pet_*.webp"))
entries = "".join(f'        "{p.stem}" to R.drawable.{p.stem},\n' for p in webps)
with open(KT, "w", encoding="utf-8", newline="\n") as f:
    f.write(KT_TEMPLATE.replace("@ENTRIES@", entries))
kb = sum(p.stat().st_size for p in webps) // 1024
print(f"converted {len(pngs)} png; PetSprites.kt lists {len(webps)} sprites, {kb} KB total")
